apiVersion: v1
kind: Pod
metadata:
  name: test-pod-running
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          touch /mnt/SUCCESS
          echo "NFS works!"
          sleep 3600
      volumeMounts:
        - name: nfs-pvc
          mountPath: /mnt
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: nfs-pvc
